In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '{:.2f}'.format(x))
import seaborn as sns
color = sns.color_palette()
sns.set_style('darkgrid')
import matplotlib.pyplot as plt
plt.rcParams["font.sans-serif"]=["SimHei"] #设 置 字 体
plt.rcParams["axes.unicode_minus"]=False #该 语 句 解 决 图 像中 的 “ -” 负 号 的 乱 码 问 题
%matplotlib inline
from scipy import stats
from scipy.special import boxcox1p
from scipy.stats import norm, skew
import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn
import scipy.stats as stats
from scipy.stats import shapiro, skew
import math
import plotly.express as px
import plotly.graph_objs as go
import plotly.subplots as sp
from plotly.subplots import make_subplots
import plotly.figure_factory as ff
from IPython.display import display
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

In [3]:
df = pd.read_excel("../Data/空气质量.xlsx")

In [5]:
df.set_index(df.date, inplace=True)
df.drop(columns='date', inplace=True)

In [33]:
# 输入参数
city_population = 1000000
electric_cars_quantity = 10000
electric_buses_quantity = 1000
average_annual_mileage = 10000  # 每辆车平均每年行驶里程
co2_reduction_per_car = 0.1  # 新能源电动汽车与传统汽车的CO2排放差，单位：吨/车·年
co2_reduction_per_bus = 10  # 电动公交车与传统公交车的CO2排放差，单位：吨/车·年

# 计算每年减少的 CO2 排放量
co2_reduction_cars = electric_cars_quantity * average_annual_mileage * co2_reduction_per_car
co2_reduction_buses = electric_buses_quantity * average_annual_mileage * co2_reduction_per_bus

# 计算总减少的 CO2 排放量
total_co2_reduction = co2_reduction_cars + co2_reduction_buses

# 打印结果
print(f"新能源电动汽车每年减少的CO2排放量：{co2_reduction_cars:.2f} 吨")
print(f"电动公交车每年减少的CO2排放量：{co2_reduction_buses:.2f} 吨")
print(f"总减少的CO2排放量：{total_co2_reduction:.2f} 吨")

新能源电动汽车每年减少的CO2排放量：10000000.00 吨
电动公交车每年减少的CO2排放量：100000000.00 吨
总减少的CO2排放量：110000000.00 吨

    Population  ElectricCarSales  AirQuality
0      1000000             19.80          66
1      1000000             23.50          56
2      1000000             19.40          72
3      1000000             12.40          94
4      1000000             21.60         149
5      1000000             21.60          71
6      1000000             21.70          84
7      1000000             24.80          85
8      1000000             30.90          71
9      1000000             30.90          72
10     1000000             35.30          57
11     1000000             39.70          50
12     1000000             45.76          75
13     1000000             51.80          55
14     1000000             45.20          68
15     1000000             36.90          47
16     1000000             46.50          70
17     1000000             31.20          74
18     1000000             46.60          86
19     1000000             59.00         102
20     1000000             61.70          86
21     1000000             84.30          67
22     1000000             75.50          91
23     1000000             76.20          65
24     1000000             76.80          71
25     1000000             79.50          57
26     1000000             42.50          61
27     1000000             55.20          80
28     1000000             67.40         117
29     1000000             64.00         105
30     1000000             71.30          91
31     1000000             78.40         112
32     1000000             80.50          93
33     1000000             84.30          71
34     1000000             87.90          70

In [24]:
import pandas as pd
import statsmodels.api as sm

# 提供的数据（示例数据，请替换为实际数据）



df = pd.DataFrame(data)

# 添加截距项
df['intercept'] = 1

# 拟合线性模型
model = sm.OLS(df['Y'], df[['intercept', 'X']])
results = model.fit()

# 打印回归系数
print("回归系数：")
print(results.params)

# 打印R方
print("\nR方：")
print(results.rsquared)

# 打印回归系数的显著性
print("\n回归系数的显著性：")
print(results.pvalues)

Mean Squared Error: 483.8133708038771
Coefficients: [0.         0.04874515]
Intercept: 77.4263188895952